[package]
name = "map_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { workspace = true }
egui = { workspace = true }
egui_extras = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
noise = "0.9"
rand = { workspace = true }
