[package]
name = "board"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs.workspace = true
thiserror.workspace = true
serde.workspace = true
toml.workspace = true
strum.workspace = true
strum_macros.workspace = true
rand.workspace = true
